from .auto_wrap import *

GL_VERSION_3_0 = 1
GL_COMPARE_REF_TO_TEXTURE = 0x884E
GL_CLIP_DISTANCE0 = 0x3000
GL_CLIP_DISTANCE1 = 0x3001
GL_CLIP_DISTANCE2 = 0x3002
GL_CLIP_DISTANCE3 = 0x3003
GL_CLIP_DISTANCE4 = 0x3004
GL_CLIP_DISTANCE5 = 0x3005
GL_CLIP_DISTANCE6 = 0x3006
GL_CLIP_DISTANCE7 = 0x3007
GL_MAX_CLIP_DISTANCES = 0x0D32
GL_MAJOR_VERSION = 0x821B
GL_MINOR_VERSION = 0x821C
GL_NUM_EXTENSIONS = 0x821D
GL_CONTEXT_FLAGS = 0x821E
GL_COMPRESSED_RED = 0x8225
GL_COMPRESSED_RG = 0x8226
GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x00000001
GL_RGBA32F = 0x8814
GL_RGB32F = 0x8815
GL_RGBA16F = 0x881A
GL_RGB16F = 0x881B
GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD
GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF
GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904
GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905
GL_CLAMP_READ_COLOR = 0x891C
GL_FIXED_ONLY = 0x891D
GL_MAX_VARYING_COMPONENTS = 0x8B4B
GL_TEXTURE_1D_ARRAY = 0x8C18
GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19
GL_TEXTURE_2D_ARRAY = 0x8C1A
GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B
GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C
GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D
GL_R11F_G11F_B10F = 0x8C3A
GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B
GL_RGB9_E5 = 0x8C3D
GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E
GL_TEXTURE_SHARED_SIZE = 0x8C3F
GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76
GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F
GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80
GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83
GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84
GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85
GL_PRIMITIVES_GENERATED = 0x8C87
GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88
GL_RASTERIZER_DISCARD = 0x8C89
GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A
GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B
GL_INTERLEAVED_ATTRIBS = 0x8C8C
GL_SEPARATE_ATTRIBS = 0x8C8D
GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E
GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F
GL_RGBA32UI = 0x8D70
GL_RGB32UI = 0x8D71
GL_RGBA16UI = 0x8D76
GL_RGB16UI = 0x8D77
GL_RGBA8UI = 0x8D7C
GL_RGB8UI = 0x8D7D
GL_RGBA32I = 0x8D82
GL_RGB32I = 0x8D83
GL_RGBA16I = 0x8D88
GL_RGB16I = 0x8D89
GL_RGBA8I = 0x8D8E
GL_RGB8I = 0x8D8F
GL_RED_INTEGER = 0x8D94
GL_GREEN_INTEGER = 0x8D95
GL_BLUE_INTEGER = 0x8D96
GL_RGB_INTEGER = 0x8D98
GL_RGBA_INTEGER = 0x8D99
GL_BGR_INTEGER = 0x8D9A
GL_BGRA_INTEGER = 0x8D9B
GL_SAMPLER_1D_ARRAY = 0x8DC0
GL_SAMPLER_2D_ARRAY = 0x8DC1
GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3
GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4
GL_SAMPLER_CUBE_SHADOW = 0x8DC5
GL_UNSIGNED_INT_VEC2 = 0x8DC6
GL_UNSIGNED_INT_VEC3 = 0x8DC7
GL_UNSIGNED_INT_VEC4 = 0x8DC8
GL_INT_SAMPLER_1D = 0x8DC9
GL_INT_SAMPLER_2D = 0x8DCA
GL_INT_SAMPLER_3D = 0x8DCB
GL_INT_SAMPLER_CUBE = 0x8DCC
GL_INT_SAMPLER_1D_ARRAY = 0x8DCE
GL_INT_SAMPLER_2D_ARRAY = 0x8DCF
GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1
GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2
GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3
GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4
GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6
GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7
GL_QUERY_WAIT = 0x8E13
GL_QUERY_NO_WAIT = 0x8E14
GL_QUERY_BY_REGION_WAIT = 0x8E15
GL_QUERY_BY_REGION_NO_WAIT = 0x8E16
GL_BUFFER_ACCESS_FLAGS = 0x911F
GL_BUFFER_MAP_LENGTH = 0x9120
GL_BUFFER_MAP_OFFSET = 0x9121
GL_DEPTH_COMPONENT32F = 0x8CAC
GL_DEPTH32F_STENCIL8 = 0x8CAD
GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD
GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506
GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210
GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211
GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212
GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213
GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214
GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215
GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216
GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217
GL_FRAMEBUFFER_DEFAULT = 0x8218
GL_FRAMEBUFFER_UNDEFINED = 0x8219
GL_DEPTH_STENCIL_ATTACHMENT = 0x821A
GL_MAX_RENDERBUFFER_SIZE = 0x84E8
GL_DEPTH_STENCIL = 0x84F9
GL_UNSIGNED_INT_24_8 = 0x84FA
GL_DEPTH24_STENCIL8 = 0x88F0
GL_TEXTURE_STENCIL_SIZE = 0x88F1
GL_TEXTURE_RED_TYPE = 0x8C10
GL_TEXTURE_GREEN_TYPE = 0x8C11
GL_TEXTURE_BLUE_TYPE = 0x8C12
GL_TEXTURE_ALPHA_TYPE = 0x8C13
GL_TEXTURE_DEPTH_TYPE = 0x8C16
GL_UNSIGNED_NORMALIZED = 0x8C17
GL_FRAMEBUFFER_BINDING = 0x8CA6
GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6
GL_RENDERBUFFER_BINDING = 0x8CA7
GL_READ_FRAMEBUFFER = 0x8CA8
GL_DRAW_FRAMEBUFFER = 0x8CA9
GL_READ_FRAMEBUFFER_BINDING = 0x8CAA
GL_RENDERBUFFER_SAMPLES = 0x8CAB
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4
GL_FRAMEBUFFER_COMPLETE = 0x8CD5
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7
GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB
GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC
GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD
GL_MAX_COLOR_ATTACHMENTS = 0x8CDF
GL_COLOR_ATTACHMENT0 = 0x8CE0
GL_COLOR_ATTACHMENT1 = 0x8CE1
GL_COLOR_ATTACHMENT2 = 0x8CE2
GL_COLOR_ATTACHMENT3 = 0x8CE3
GL_COLOR_ATTACHMENT4 = 0x8CE4
GL_COLOR_ATTACHMENT5 = 0x8CE5
GL_COLOR_ATTACHMENT6 = 0x8CE6
GL_COLOR_ATTACHMENT7 = 0x8CE7
GL_COLOR_ATTACHMENT8 = 0x8CE8
GL_COLOR_ATTACHMENT9 = 0x8CE9
GL_COLOR_ATTACHMENT10 = 0x8CEA
GL_COLOR_ATTACHMENT11 = 0x8CEB
GL_COLOR_ATTACHMENT12 = 0x8CEC
GL_COLOR_ATTACHMENT13 = 0x8CED
GL_COLOR_ATTACHMENT14 = 0x8CEE
GL_COLOR_ATTACHMENT15 = 0x8CEF
GL_COLOR_ATTACHMENT16 = 0x8CF0
GL_COLOR_ATTACHMENT17 = 0x8CF1
GL_COLOR_ATTACHMENT18 = 0x8CF2
GL_COLOR_ATTACHMENT19 = 0x8CF3
GL_COLOR_ATTACHMENT20 = 0x8CF4
GL_COLOR_ATTACHMENT21 = 0x8CF5
GL_COLOR_ATTACHMENT22 = 0x8CF6
GL_COLOR_ATTACHMENT23 = 0x8CF7
GL_COLOR_ATTACHMENT24 = 0x8CF8
GL_COLOR_ATTACHMENT25 = 0x8CF9
GL_COLOR_ATTACHMENT26 = 0x8CFA
GL_COLOR_ATTACHMENT27 = 0x8CFB
GL_COLOR_ATTACHMENT28 = 0x8CFC
GL_COLOR_ATTACHMENT29 = 0x8CFD
GL_COLOR_ATTACHMENT30 = 0x8CFE
GL_COLOR_ATTACHMENT31 = 0x8CFF
GL_DEPTH_ATTACHMENT = 0x8D00
GL_STENCIL_ATTACHMENT = 0x8D20
GL_FRAMEBUFFER = 0x8D40
GL_RENDERBUFFER = 0x8D41
GL_RENDERBUFFER_WIDTH = 0x8D42
GL_RENDERBUFFER_HEIGHT = 0x8D43
GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44
GL_STENCIL_INDEX1 = 0x8D46
GL_STENCIL_INDEX4 = 0x8D47
GL_STENCIL_INDEX8 = 0x8D48
GL_STENCIL_INDEX16 = 0x8D49
GL_RENDERBUFFER_RED_SIZE = 0x8D50
GL_RENDERBUFFER_GREEN_SIZE = 0x8D51
GL_RENDERBUFFER_BLUE_SIZE = 0x8D52
GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53
GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54
GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56
GL_MAX_SAMPLES = 0x8D57
GL_FRAMEBUFFER_SRGB = 0x8DB9
GL_HALF_FLOAT = 0x140B
GL_MAP_READ_BIT = 0x0001
GL_MAP_WRITE_BIT = 0x0002
GL_MAP_INVALIDATE_RANGE_BIT = 0x0004
GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008
GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010
GL_MAP_UNSYNCHRONIZED_BIT = 0x0020
GL_COMPRESSED_RED_RGTC1 = 0x8DBB
GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC
GL_COMPRESSED_RG_RGTC2 = 0x8DBD
GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE
GL_RG = 0x8227
GL_RG_INTEGER = 0x8228
GL_R8 = 0x8229
GL_R16 = 0x822A
GL_RG8 = 0x822B
GL_RG16 = 0x822C
GL_R16F = 0x822D
GL_R32F = 0x822E
GL_RG16F = 0x822F
GL_RG32F = 0x8230
GL_R8I = 0x8231
GL_R8UI = 0x8232
GL_R16I = 0x8233
GL_R16UI = 0x8234
GL_R32I = 0x8235
GL_R32UI = 0x8236
GL_RG8I = 0x8237
GL_RG8UI = 0x8238
GL_RG16I = 0x8239
GL_RG16UI = 0x823A
GL_RG32I = 0x823B
GL_RG32UI = 0x823C
GL_VERTEX_ARRAY_BINDING = 0x85B5
PFNGLCOLORMASKIPROC = C(None, UInt, UByte, UByte, UByte, UByte)
PFNGLGETBOOLEANI_VPROC = C(None, UInt, UInt, P(UByte))
PFNGLGETINTEGERI_VPROC = C(None, UInt, UInt, P(Int))
PFNGLENABLEIPROC = C(None, UInt, UInt)
PFNGLDISABLEIPROC = C(None, UInt, UInt)
PFNGLISENABLEDIPROC = C(UByte, UInt, UInt)
PFNGLBEGINTRANSFORMFEEDBACKPROC = C(None, UInt)
PFNGLENDTRANSFORMFEEDBACKPROC = C(None)
PFNGLBINDBUFFERRANGEPROC = C(None, UInt, UInt, UInt, Size, Size)
PFNGLBINDBUFFERBASEPROC = C(None, UInt, UInt, UInt)
PFNGLTRANSFORMFEEDBACKVARYINGSPROC = C(None, UInt, Int, P(CharP), UInt)
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC = C(
    None, UInt, UInt, Int, P(Int), P(Int), P(UInt), CharP)
PFNGLCLAMPCOLORPROC = C(None, UInt, UInt)
PFNGLBEGINCONDITIONALRENDERPROC = C(None, UInt, UInt)
PFNGLENDCONDITIONALRENDERPROC = C(None)
PFNGLVERTEXATTRIBIPOINTERPROC = C(None, UInt, Int, UInt, Int, VoidP)
PFNGLGETVERTEXATTRIBIIVPROC = C(None, UInt, UInt, P(Int))
PFNGLGETVERTEXATTRIBIUIVPROC = C(None, UInt, UInt, P(UInt))
PFNGLVERTEXATTRIBI1IPROC = C(None, UInt, Int)
PFNGLVERTEXATTRIBI2IPROC = C(None, UInt, Int, Int)
PFNGLVERTEXATTRIBI3IPROC = C(None, UInt, Int, Int, Int)
PFNGLVERTEXATTRIBI4IPROC = C(None, UInt, Int, Int, Int, Int)
PFNGLVERTEXATTRIBI1UIPROC = C(None, UInt, UInt)
PFNGLVERTEXATTRIBI2UIPROC = C(None, UInt, UInt, UInt)
PFNGLVERTEXATTRIBI3UIPROC = C(None, UInt, UInt, UInt, UInt)
PFNGLVERTEXATTRIBI4UIPROC = C(None, UInt, UInt, UInt, UInt, UInt)
PFNGLVERTEXATTRIBI1IVPROC = C(None, UInt, P(Int))
PFNGLVERTEXATTRIBI2IVPROC = C(None, UInt, P(Int))
PFNGLVERTEXATTRIBI3IVPROC = C(None, UInt, P(Int))
PFNGLVERTEXATTRIBI4IVPROC = C(None, UInt, P(Int))
PFNGLVERTEXATTRIBI1UIVPROC = C(None, UInt, P(UInt))
PFNGLVERTEXATTRIBI2UIVPROC = C(None, UInt, P(UInt))
PFNGLVERTEXATTRIBI3UIVPROC = C(None, UInt, P(UInt))
PFNGLVERTEXATTRIBI4UIVPROC = C(None, UInt, P(UInt))
PFNGLVERTEXATTRIBI4BVPROC = C(None, UInt, P(Byte))
PFNGLVERTEXATTRIBI4SVPROC = C(None, UInt, P(Short))
PFNGLVERTEXATTRIBI4UBVPROC = C(None, UInt, P(UByte))
PFNGLVERTEXATTRIBI4USVPROC = C(None, UInt, P(UShort))
PFNGLGETUNIFORMUIVPROC = C(None, UInt, Int, P(UInt))
PFNGLBINDFRAGDATALOCATIONPROC = C(None, UInt, UInt, CharP)
PFNGLGETFRAGDATALOCATIONPROC = C(Int, UInt, CharP)
PFNGLUNIFORM1UIPROC = C(None, Int, UInt)
PFNGLUNIFORM2UIPROC = C(None, Int, UInt, UInt)
PFNGLUNIFORM3UIPROC = C(None, Int, UInt, UInt, UInt)
PFNGLUNIFORM4UIPROC = C(None, Int, UInt, UInt, UInt, UInt)
PFNGLUNIFORM1UIVPROC = C(None, Int, Int, P(UInt))
PFNGLUNIFORM2UIVPROC = C(None, Int, Int, P(UInt))
PFNGLUNIFORM3UIVPROC = C(None, Int, Int, P(UInt))
PFNGLUNIFORM4UIVPROC = C(None, Int, Int, P(UInt))
PFNGLTEXPARAMETERIIVPROC = C(None, UInt, UInt, P(Int))
PFNGLTEXPARAMETERIUIVPROC = C(None, UInt, UInt, P(UInt))
PFNGLGETTEXPARAMETERIIVPROC = C(None, UInt, UInt, P(Int))
PFNGLGETTEXPARAMETERIUIVPROC = C(None, UInt, UInt, P(UInt))
PFNGLCLEARBUFFERIVPROC = C(None, UInt, Int, P(Int))
PFNGLCLEARBUFFERUIVPROC = C(None, UInt, Int, P(UInt))
PFNGLCLEARBUFFERFVPROC = C(None, UInt, Int, P(Float))
PFNGLCLEARBUFFERFIPROC = C(None, UInt, Int, Float, Int)
PFNGLGETSTRINGIPROC = C(P(UByte), UInt, UInt)
PFNGLISRENDERBUFFERPROC = C(UByte, UInt)
PFNGLBINDRENDERBUFFERPROC = C(None, UInt, UInt)
PFNGLDELETERENDERBUFFERSPROC = C(None, Int, P(UInt))
PFNGLGENRENDERBUFFERSPROC = C(None, Int, P(UInt))
PFNGLRENDERBUFFERSTORAGEPROC = C(None, UInt, UInt, Int, Int)
PFNGLGETRENDERBUFFERPARAMETERIVPROC = C(None, UInt, UInt, P(Int))
PFNGLISFRAMEBUFFERPROC = C(UByte, UInt)
PFNGLBINDFRAMEBUFFERPROC = C(None, UInt, UInt)
PFNGLDELETEFRAMEBUFFERSPROC = C(None, Int, P(UInt))
PFNGLGENFRAMEBUFFERSPROC = C(None, Int, P(UInt))
PFNGLCHECKFRAMEBUFFERSTATUSPROC = C(UInt, UInt)
PFNGLFRAMEBUFFERTEXTURE1DPROC = C(None, UInt, UInt, UInt, UInt, Int)
PFNGLFRAMEBUFFERTEXTURE2DPROC = C(None, UInt, UInt, UInt, UInt, Int)
PFNGLFRAMEBUFFERTEXTURE3DPROC = C(None, UInt, UInt, UInt, UInt, Int, Int)
PFNGLFRAMEBUFFERRENDERBUFFERPROC = C(None, UInt, UInt, UInt, UInt)
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC = C(
    None, UInt, UInt, UInt, P(Int))
PFNGLGENERATEMIPMAPPROC = C(None, UInt)
PFNGLBLITFRAMEBUFFERPROC = C(
    None, Int, Int, Int, Int, Int, Int, Int, Int, UInt, UInt)
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC = C(None, UInt, Int, UInt, Int, Int)
PFNGLFRAMEBUFFERTEXTURELAYERPROC = C(None, UInt, UInt, UInt, Int, Int)
PFNGLMAPBUFFERRANGEPROC = C(VoidP, UInt, Size, Size, UInt)
PFNGLFLUSHMAPPEDBUFFERRANGEPROC = C(None, UInt, Size, Size)
PFNGLBINDVERTEXARRAYPROC = C(None, UInt)
PFNGLDELETEVERTEXARRAYSPROC = C(None, Int, P(UInt))
PFNGLGENVERTEXARRAYSPROC = C(None, Int, P(UInt))
PFNGLISVERTEXARRAYPROC = C(UByte, UInt)
glColorMaski = E('glColorMaski', None, UInt, UByte, UByte, UByte, UByte)
glGetBooleani_v = E('glGetBooleani_v', None, UInt, UInt, P(UByte))
glGetIntegeri_v = E('glGetIntegeri_v', None, UInt, UInt, P(Int))
glEnablei = E('glEnablei', None, UInt, UInt)
glDisablei = E('glDisablei', None, UInt, UInt)
glIsEnabledi = E('glIsEnabledi', UByte, UInt, UInt)
glBeginTransformFeedback = E('glBeginTransformFeedback', None, UInt)
glEndTransformFeedback = E('glEndTransformFeedback', None)
glBindBufferRange = E('glBindBufferRange', None, UInt, UInt, UInt, Size, Size)
glBindBufferBase = E('glBindBufferBase', None, UInt, UInt, UInt)
glTransformFeedbackVaryings = E(
    'glTransformFeedbackVaryings', None, UInt, Int, P(CharP), UInt)
glGetTransformFeedbackVarying = E('glGetTransformFeedbackVarying', None, UInt,
                                  UInt, Int, P(Int), P(Int), P(UInt), CharP)
glClampColor = E('glClampColor', None, UInt, UInt)
glBeginConditionalRender = E('glBeginConditionalRender', None, UInt, UInt)
glEndConditionalRender = E('glEndConditionalRender', None)
glVertexAttribIPointer = E(
    'glVertexAttribIPointer', None, UInt, Int, UInt, Int, VoidP)
glGetVertexAttribIiv = E('glGetVertexAttribIiv', None, UInt, UInt, P(Int))
glGetVertexAttribIuiv = E('glGetVertexAttribIuiv', None, UInt, UInt, P(UInt))
glVertexAttribI1i = E('glVertexAttribI1i', None, UInt, Int)
glVertexAttribI2i = E('glVertexAttribI2i', None, UInt, Int, Int)
glVertexAttribI3i = E('glVertexAttribI3i', None, UInt, Int, Int, Int)
glVertexAttribI4i = E('glVertexAttribI4i', None, UInt, Int, Int, Int, Int)
glVertexAttribI1ui = E('glVertexAttribI1ui', None, UInt, UInt)
glVertexAttribI2ui = E('glVertexAttribI2ui', None, UInt, UInt, UInt)
glVertexAttribI3ui = E('glVertexAttribI3ui', None, UInt, UInt, UInt, UInt)
glVertexAttribI4ui = E(
    'glVertexAttribI4ui', None, UInt, UInt, UInt, UInt, UInt)
glVertexAttribI1iv = E('glVertexAttribI1iv', None, UInt, P(Int))
glVertexAttribI2iv = E('glVertexAttribI2iv', None, UInt, P(Int))
glVertexAttribI3iv = E('glVertexAttribI3iv', None, UInt, P(Int))
glVertexAttribI4iv = E('glVertexAttribI4iv', None, UInt, P(Int))
glVertexAttribI1uiv = E('glVertexAttribI1uiv', None, UInt, P(UInt))
glVertexAttribI2uiv = E('glVertexAttribI2uiv', None, UInt, P(UInt))
glVertexAttribI3uiv = E('glVertexAttribI3uiv', None, UInt, P(UInt))
glVertexAttribI4uiv = E('glVertexAttribI4uiv', None, UInt, P(UInt))
glVertexAttribI4bv = E('glVertexAttribI4bv', None, UInt, P(Byte))
glVertexAttribI4sv = E('glVertexAttribI4sv', None, UInt, P(Short))
glVertexAttribI4ubv = E('glVertexAttribI4ubv', None, UInt, P(UByte))
glVertexAttribI4usv = E('glVertexAttribI4usv', None, UInt, P(UShort))
glGetUniformuiv = E('glGetUniformuiv', None, UInt, Int, P(UInt))
glBindFragDataLocation = E('glBindFragDataLocation', None, UInt, UInt, CharP)
glGetFragDataLocation = E('glGetFragDataLocation', Int, UInt, CharP)
glUniform1ui = E('glUniform1ui', None, Int, UInt)
glUniform2ui = E('glUniform2ui', None, Int, UInt, UInt)
glUniform3ui = E('glUniform3ui', None, Int, UInt, UInt, UInt)
glUniform4ui = E('glUniform4ui', None, Int, UInt, UInt, UInt, UInt)
glUniform1uiv = E('glUniform1uiv', None, Int, Int, P(UInt))
glUniform2uiv = E('glUniform2uiv', None, Int, Int, P(UInt))
glUniform3uiv = E('glUniform3uiv', None, Int, Int, P(UInt))
glUniform4uiv = E('glUniform4uiv', None, Int, Int, P(UInt))
glTexParameterIiv = E('glTexParameterIiv', None, UInt, UInt, P(Int))
glTexParameterIuiv = E('glTexParameterIuiv', None, UInt, UInt, P(UInt))
glGetTexParameterIiv = E('glGetTexParameterIiv', None, UInt, UInt, P(Int))
glGetTexParameterIuiv = E('glGetTexParameterIuiv', None, UInt, UInt, P(UInt))
glClearBufferiv = E('glClearBufferiv', None, UInt, Int, P(Int))
glClearBufferuiv = E('glClearBufferuiv', None, UInt, Int, P(UInt))
glClearBufferfv = E('glClearBufferfv', None, UInt, Int, P(Float))
glClearBufferfi = E('glClearBufferfi', None, UInt, Int, Float, Int)
glGetStringi = E('glGetStringi', P(UByte), UInt, UInt)
glIsRenderbuffer = E('glIsRenderbuffer', UByte, UInt)
glBindRenderbuffer = E('glBindRenderbuffer', None, UInt, UInt)
glDeleteRenderbuffers = E('glDeleteRenderbuffers', None, Int, P(UInt))
glGenRenderbuffers = E('glGenRenderbuffers', None, Int, P(UInt))
glRenderbufferStorage = E('glRenderbufferStorage', None, UInt, UInt, Int, Int)
glGetRenderbufferParameteriv = E(
    'glGetRenderbufferParameteriv', None, UInt, UInt, P(Int))
glIsFramebuffer = E('glIsFramebuffer', UByte, UInt)
glBindFramebuffer = E('glBindFramebuffer', None, UInt, UInt)
glDeleteFramebuffers = E('glDeleteFramebuffers', None, Int, P(UInt))
glGenFramebuffers = E('glGenFramebuffers', None, Int, P(UInt))
glCheckFramebufferStatus = E('glCheckFramebufferStatus', UInt, UInt)
glFramebufferTexture1D = E(
    'glFramebufferTexture1D', None, UInt, UInt, UInt, UInt, Int)
glFramebufferTexture2D = E(
    'glFramebufferTexture2D', None, UInt, UInt, UInt, UInt, Int)
glFramebufferTexture3D = E(
    'glFramebufferTexture3D', None, UInt, UInt, UInt, UInt, Int, Int)
glFramebufferRenderbuffer = E(
    'glFramebufferRenderbuffer', None, UInt, UInt, UInt, UInt)
glGetFramebufferAttachmentParameteriv = E(
    'glGetFramebufferAttachmentParameteriv', None, UInt, UInt, UInt, P(Int))
glGenerateMipmap = E('glGenerateMipmap', None, UInt)
glBlitFramebuffer = E('glBlitFramebuffer', None, Int, Int, Int, Int, Int, Int,
                      Int, Int, UInt, UInt)
glRenderbufferStorageMultisample = E(
    'glRenderbufferStorageMultisample', None, UInt, Int, UInt, Int, Int)
glFramebufferTextureLayer = E(
    'glFramebufferTextureLayer', None, UInt, UInt, UInt, Int, Int)
glMapBufferRange = E('glMapBufferRange', VoidP, UInt, Size, Size, UInt)
glFlushMappedBufferRange = E(
    'glFlushMappedBufferRange', None, UInt, Size, Size)
glBindVertexArray = E('glBindVertexArray', None, UInt)
glDeleteVertexArrays = E('glDeleteVertexArrays', None, Int, P(UInt))
glGenVertexArrays = E('glGenVertexArrays', None, Int, P(UInt))
glIsVertexArray = E('glIsVertexArray', UByte, UInt)

__all__ = [
    'GL_VERSION_3_0', 'GL_COMPARE_REF_TO_TEXTURE', 'GL_CLIP_DISTANCE0',
    'GL_CLIP_DISTANCE1', 'GL_CLIP_DISTANCE2', 'GL_CLIP_DISTANCE3',
    'GL_CLIP_DISTANCE4', 'GL_CLIP_DISTANCE5', 'GL_CLIP_DISTANCE6',
    'GL_CLIP_DISTANCE7', 'GL_MAX_CLIP_DISTANCES', 'GL_MAJOR_VERSION',
    'GL_MINOR_VERSION', 'GL_NUM_EXTENSIONS', 'GL_CONTEXT_FLAGS',
    'GL_COMPRESSED_RED', 'GL_COMPRESSED_RG',
    'GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT', 'GL_RGBA32F', 'GL_RGB32F',
    'GL_RGBA16F', 'GL_RGB16F', 'GL_VERTEX_ATTRIB_ARRAY_INTEGER',
    'GL_MAX_ARRAY_TEXTURE_LAYERS', 'GL_MIN_PROGRAM_TEXEL_OFFSET',
    'GL_MAX_PROGRAM_TEXEL_OFFSET', 'GL_CLAMP_READ_COLOR', 'GL_FIXED_ONLY',
    'GL_MAX_VARYING_COMPONENTS', 'GL_TEXTURE_1D_ARRAY',
    'GL_PROXY_TEXTURE_1D_ARRAY', 'GL_TEXTURE_2D_ARRAY',
    'GL_PROXY_TEXTURE_2D_ARRAY', 'GL_TEXTURE_BINDING_1D_ARRAY',
    'GL_TEXTURE_BINDING_2D_ARRAY', 'GL_R11F_G11F_B10F',
    'GL_UNSIGNED_INT_10F_11F_11F_REV', 'GL_RGB9_E5',
    'GL_UNSIGNED_INT_5_9_9_9_REV', 'GL_TEXTURE_SHARED_SIZE',
    'GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH',
    'GL_TRANSFORM_FEEDBACK_BUFFER_MODE',
    'GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS',
    'GL_TRANSFORM_FEEDBACK_VARYINGS', 'GL_TRANSFORM_FEEDBACK_BUFFER_START',
    'GL_TRANSFORM_FEEDBACK_BUFFER_SIZE', 'GL_PRIMITIVES_GENERATED',
    'GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN', 'GL_RASTERIZER_DISCARD',
    'GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS',
    'GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS', 'GL_INTERLEAVED_ATTRIBS',
    'GL_SEPARATE_ATTRIBS', 'GL_TRANSFORM_FEEDBACK_BUFFER',
    'GL_TRANSFORM_FEEDBACK_BUFFER_BINDING', 'GL_RGBA32UI', 'GL_RGB32UI',
    'GL_RGBA16UI', 'GL_RGB16UI', 'GL_RGBA8UI', 'GL_RGB8UI', 'GL_RGBA32I',
    'GL_RGB32I', 'GL_RGBA16I', 'GL_RGB16I', 'GL_RGBA8I', 'GL_RGB8I',
    'GL_RED_INTEGER', 'GL_GREEN_INTEGER', 'GL_BLUE_INTEGER', 'GL_RGB_INTEGER',
    'GL_RGBA_INTEGER', 'GL_BGR_INTEGER', 'GL_BGRA_INTEGER',
    'GL_SAMPLER_1D_ARRAY', 'GL_SAMPLER_2D_ARRAY',
    'GL_SAMPLER_1D_ARRAY_SHADOW', 'GL_SAMPLER_2D_ARRAY_SHADOW',
    'GL_SAMPLER_CUBE_SHADOW', 'GL_UNSIGNED_INT_VEC2', 'GL_UNSIGNED_INT_VEC3',
    'GL_UNSIGNED_INT_VEC4', 'GL_INT_SAMPLER_1D', 'GL_INT_SAMPLER_2D',
    'GL_INT_SAMPLER_3D', 'GL_INT_SAMPLER_CUBE', 'GL_INT_SAMPLER_1D_ARRAY',
    'GL_INT_SAMPLER_2D_ARRAY', 'GL_UNSIGNED_INT_SAMPLER_1D',
    'GL_UNSIGNED_INT_SAMPLER_2D', 'GL_UNSIGNED_INT_SAMPLER_3D',
    'GL_UNSIGNED_INT_SAMPLER_CUBE', 'GL_UNSIGNED_INT_SAMPLER_1D_ARRAY',
    'GL_UNSIGNED_INT_SAMPLER_2D_ARRAY', 'GL_QUERY_WAIT', 'GL_QUERY_NO_WAIT',
    'GL_QUERY_BY_REGION_WAIT', 'GL_QUERY_BY_REGION_NO_WAIT',
    'GL_BUFFER_ACCESS_FLAGS', 'GL_BUFFER_MAP_LENGTH', 'GL_BUFFER_MAP_OFFSET',
    'GL_DEPTH_COMPONENT32F', 'GL_DEPTH32F_STENCIL8',
    'GL_FLOAT_32_UNSIGNED_INT_24_8_REV', 'GL_INVALID_FRAMEBUFFER_OPERATION',
    'GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING',
    'GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE',
    'GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE',
    'GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE',
    'GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE',
    'GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE',
    'GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE',
    'GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE', 'GL_FRAMEBUFFER_DEFAULT',
    'GL_FRAMEBUFFER_UNDEFINED', 'GL_DEPTH_STENCIL_ATTACHMENT',
    'GL_MAX_RENDERBUFFER_SIZE', 'GL_DEPTH_STENCIL', 'GL_UNSIGNED_INT_24_8',
    'GL_DEPTH24_STENCIL8', 'GL_TEXTURE_STENCIL_SIZE', 'GL_TEXTURE_RED_TYPE',
    'GL_TEXTURE_GREEN_TYPE', 'GL_TEXTURE_BLUE_TYPE', 'GL_TEXTURE_ALPHA_TYPE',
    'GL_TEXTURE_DEPTH_TYPE', 'GL_UNSIGNED_NORMALIZED',
    'GL_FRAMEBUFFER_BINDING', 'GL_DRAW_FRAMEBUFFER_BINDING',
    'GL_RENDERBUFFER_BINDING', 'GL_READ_FRAMEBUFFER', 'GL_DRAW_FRAMEBUFFER',
    'GL_READ_FRAMEBUFFER_BINDING', 'GL_RENDERBUFFER_SAMPLES',
    'GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE',
    'GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME',
    'GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL',
    'GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE',
    'GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER', 'GL_FRAMEBUFFER_COMPLETE',
    'GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT',
    'GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT',
    'GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER',
    'GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER', 'GL_FRAMEBUFFER_UNSUPPORTED',
    'GL_MAX_COLOR_ATTACHMENTS', 'GL_COLOR_ATTACHMENT0',
    'GL_COLOR_ATTACHMENT1', 'GL_COLOR_ATTACHMENT2', 'GL_COLOR_ATTACHMENT3',
    'GL_COLOR_ATTACHMENT4', 'GL_COLOR_ATTACHMENT5', 'GL_COLOR_ATTACHMENT6',
    'GL_COLOR_ATTACHMENT7', 'GL_COLOR_ATTACHMENT8', 'GL_COLOR_ATTACHMENT9',
    'GL_COLOR_ATTACHMENT10', 'GL_COLOR_ATTACHMENT11', 'GL_COLOR_ATTACHMENT12',
    'GL_COLOR_ATTACHMENT13', 'GL_COLOR_ATTACHMENT14', 'GL_COLOR_ATTACHMENT15',
    'GL_COLOR_ATTACHMENT16', 'GL_COLOR_ATTACHMENT17', 'GL_COLOR_ATTACHMENT18',
    'GL_COLOR_ATTACHMENT19', 'GL_COLOR_ATTACHMENT20', 'GL_COLOR_ATTACHMENT21',
    'GL_COLOR_ATTACHMENT22', 'GL_COLOR_ATTACHMENT23', 'GL_COLOR_ATTACHMENT24',
    'GL_COLOR_ATTACHMENT25', 'GL_COLOR_ATTACHMENT26', 'GL_COLOR_ATTACHMENT27',
    'GL_COLOR_ATTACHMENT28', 'GL_COLOR_ATTACHMENT29', 'GL_COLOR_ATTACHMENT30',
    'GL_COLOR_ATTACHMENT31', 'GL_DEPTH_ATTACHMENT', 'GL_STENCIL_ATTACHMENT',
    'GL_FRAMEBUFFER', 'GL_RENDERBUFFER', 'GL_RENDERBUFFER_WIDTH',
    'GL_RENDERBUFFER_HEIGHT', 'GL_RENDERBUFFER_INTERNAL_FORMAT',
    'GL_STENCIL_INDEX1', 'GL_STENCIL_INDEX4', 'GL_STENCIL_INDEX8',
    'GL_STENCIL_INDEX16', 'GL_RENDERBUFFER_RED_SIZE',
    'GL_RENDERBUFFER_GREEN_SIZE', 'GL_RENDERBUFFER_BLUE_SIZE',
    'GL_RENDERBUFFER_ALPHA_SIZE', 'GL_RENDERBUFFER_DEPTH_SIZE',
    'GL_RENDERBUFFER_STENCIL_SIZE', 'GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE',
    'GL_MAX_SAMPLES', 'GL_FRAMEBUFFER_SRGB', 'GL_HALF_FLOAT',
    'GL_MAP_READ_BIT', 'GL_MAP_WRITE_BIT', 'GL_MAP_INVALIDATE_RANGE_BIT',
    'GL_MAP_INVALIDATE_BUFFER_BIT', 'GL_MAP_FLUSH_EXPLICIT_BIT',
    'GL_MAP_UNSYNCHRONIZED_BIT', 'GL_COMPRESSED_RED_RGTC1',
    'GL_COMPRESSED_SIGNED_RED_RGTC1', 'GL_COMPRESSED_RG_RGTC2',
    'GL_COMPRESSED_SIGNED_RG_RGTC2', 'GL_RG', 'GL_RG_INTEGER', 'GL_R8',
    'GL_R16', 'GL_RG8', 'GL_RG16', 'GL_R16F', 'GL_R32F', 'GL_RG16F',
    'GL_RG32F', 'GL_R8I', 'GL_R8UI', 'GL_R16I', 'GL_R16UI', 'GL_R32I',
    'GL_R32UI', 'GL_RG8I', 'GL_RG8UI', 'GL_RG16I', 'GL_RG16UI', 'GL_RG32I',
    'GL_RG32UI', 'GL_VERTEX_ARRAY_BINDING', 'PFNGLCOLORMASKIPROC',
    'PFNGLGETBOOLEANI_VPROC', 'PFNGLGETINTEGERI_VPROC', 'PFNGLENABLEIPROC',
    'PFNGLDISABLEIPROC', 'PFNGLISENABLEDIPROC',
    'PFNGLBEGINTRANSFORMFEEDBACKPROC', 'PFNGLENDTRANSFORMFEEDBACKPROC',
    'PFNGLBINDBUFFERRANGEPROC', 'PFNGLBINDBUFFERBASEPROC',
    'PFNGLTRANSFORMFEEDBACKVARYINGSPROC',
    'PFNGLGETTRANSFORMFEEDBACKVARYINGPROC', 'PFNGLCLAMPCOLORPROC',
    'PFNGLBEGINCONDITIONALRENDERPROC', 'PFNGLENDCONDITIONALRENDERPROC',
    'PFNGLVERTEXATTRIBIPOINTERPROC', 'PFNGLGETVERTEXATTRIBIIVPROC',
    'PFNGLGETVERTEXATTRIBIUIVPROC', 'PFNGLVERTEXATTRIBI1IPROC',
    'PFNGLVERTEXATTRIBI2IPROC', 'PFNGLVERTEXATTRIBI3IPROC',
    'PFNGLVERTEXATTRIBI4IPROC', 'PFNGLVERTEXATTRIBI1UIPROC',
    'PFNGLVERTEXATTRIBI2UIPROC', 'PFNGLVERTEXATTRIBI3UIPROC',
    'PFNGLVERTEXATTRIBI4UIPROC', 'PFNGLVERTEXATTRIBI1IVPROC',
    'PFNGLVERTEXATTRIBI2IVPROC', 'PFNGLVERTEXATTRIBI3IVPROC',
    'PFNGLVERTEXATTRIBI4IVPROC', 'PFNGLVERTEXATTRIBI1UIVPROC',
    'PFNGLVERTEXATTRIBI2UIVPROC', 'PFNGLVERTEXATTRIBI3UIVPROC',
    'PFNGLVERTEXATTRIBI4UIVPROC', 'PFNGLVERTEXATTRIBI4BVPROC',
    'PFNGLVERTEXATTRIBI4SVPROC', 'PFNGLVERTEXATTRIBI4UBVPROC',
    'PFNGLVERTEXATTRIBI4USVPROC', 'PFNGLGETUNIFORMUIVPROC',
    'PFNGLBINDFRAGDATALOCATIONPROC', 'PFNGLGETFRAGDATALOCATIONPROC',
    'PFNGLUNIFORM1UIPROC', 'PFNGLUNIFORM2UIPROC', 'PFNGLUNIFORM3UIPROC',
    'PFNGLUNIFORM4UIPROC', 'PFNGLUNIFORM1UIVPROC', 'PFNGLUNIFORM2UIVPROC',
    'PFNGLUNIFORM3UIVPROC', 'PFNGLUNIFORM4UIVPROC',
    'PFNGLTEXPARAMETERIIVPROC', 'PFNGLTEXPARAMETERIUIVPROC',
    'PFNGLGETTEXPARAMETERIIVPROC', 'PFNGLGETTEXPARAMETERIUIVPROC',
    'PFNGLCLEARBUFFERIVPROC', 'PFNGLCLEARBUFFERUIVPROC',
    'PFNGLCLEARBUFFERFVPROC', 'PFNGLCLEARBUFFERFIPROC', 'PFNGLGETSTRINGIPROC',
    'PFNGLISRENDERBUFFERPROC', 'PFNGLBINDRENDERBUFFERPROC',
    'PFNGLDELETERENDERBUFFERSPROC', 'PFNGLGENRENDERBUFFERSPROC',
    'PFNGLRENDERBUFFERSTORAGEPROC', 'PFNGLGETRENDERBUFFERPARAMETERIVPROC',
    'PFNGLISFRAMEBUFFERPROC', 'PFNGLBINDFRAMEBUFFERPROC',
    'PFNGLDELETEFRAMEBUFFERSPROC', 'PFNGLGENFRAMEBUFFERSPROC',
    'PFNGLCHECKFRAMEBUFFERSTATUSPROC', 'PFNGLFRAMEBUFFERTEXTURE1DPROC',
    'PFNGLFRAMEBUFFERTEXTURE2DPROC', 'PFNGLFRAMEBUFFERTEXTURE3DPROC',
    'PFNGLFRAMEBUFFERRENDERBUFFERPROC',
    'PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC', 'PFNGLGENERATEMIPMAPPROC',
    'PFNGLBLITFRAMEBUFFERPROC', 'PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC',
    'PFNGLFRAMEBUFFERTEXTURELAYERPROC', 'PFNGLMAPBUFFERRANGEPROC',
    'PFNGLFLUSHMAPPEDBUFFERRANGEPROC', 'PFNGLBINDVERTEXARRAYPROC',
    'PFNGLDELETEVERTEXARRAYSPROC', 'PFNGLGENVERTEXARRAYSPROC',
    'PFNGLISVERTEXARRAYPROC', 'glColorMaski', 'glGetBooleani_v',
    'glGetIntegeri_v', 'glEnablei', 'glDisablei', 'glIsEnabledi',
    'glBeginTransformFeedback', 'glEndTransformFeedback', 'glBindBufferRange',
    'glBindBufferBase', 'glTransformFeedbackVaryings',
    'glGetTransformFeedbackVarying', 'glClampColor',
    'glBeginConditionalRender', 'glEndConditionalRender',
    'glVertexAttribIPointer', 'glGetVertexAttribIiv', 'glGetVertexAttribIuiv',
    'glVertexAttribI1i', 'glVertexAttribI2i', 'glVertexAttribI3i',
    'glVertexAttribI4i', 'glVertexAttribI1ui', 'glVertexAttribI2ui',
    'glVertexAttribI3ui', 'glVertexAttribI4ui', 'glVertexAttribI1iv',
    'glVertexAttribI2iv', 'glVertexAttribI3iv', 'glVertexAttribI4iv',
    'glVertexAttribI1uiv', 'glVertexAttribI2uiv', 'glVertexAttribI3uiv',
    'glVertexAttribI4uiv', 'glVertexAttribI4bv', 'glVertexAttribI4sv',
    'glVertexAttribI4ubv', 'glVertexAttribI4usv', 'glGetUniformuiv',
    'glBindFragDataLocation', 'glGetFragDataLocation', 'glUniform1ui',
    'glUniform2ui', 'glUniform3ui', 'glUniform4ui', 'glUniform1uiv',
    'glUniform2uiv', 'glUniform3uiv', 'glUniform4uiv', 'glTexParameterIiv',
    'glTexParameterIuiv', 'glGetTexParameterIiv', 'glGetTexParameterIuiv',
    'glClearBufferiv', 'glClearBufferuiv', 'glClearBufferfv',
    'glClearBufferfi', 'glGetStringi', 'glIsRenderbuffer',
    'glBindRenderbuffer', 'glDeleteRenderbuffers', 'glGenRenderbuffers',
    'glRenderbufferStorage', 'glGetRenderbufferParameteriv',
    'glIsFramebuffer', 'glBindFramebuffer', 'glDeleteFramebuffers',
    'glGenFramebuffers', 'glCheckFramebufferStatus', 'glFramebufferTexture1D',
    'glFramebufferTexture2D', 'glFramebufferTexture3D',
    'glFramebufferRenderbuffer', 'glGetFramebufferAttachmentParameteriv',
    'glGenerateMipmap', 'glBlitFramebuffer',
    'glRenderbufferStorageMultisample', 'glFramebufferTextureLayer',
    'glMapBufferRange', 'glFlushMappedBufferRange', 'glBindVertexArray',
    'glDeleteVertexArrays', 'glGenVertexArrays', 'glIsVertexArray'
]
