from .auto_wrap import *

GL_VERSION_4_3 = 1
GLDEBUGPROC = C(None, UInt, UInt, UInt, UInt, Int, CharP, VoidP)
GL_NUM_SHADING_LANGUAGE_VERSIONS = 0x82E9
GL_VERTEX_ATTRIB_ARRAY_LONG = 0x874E
GL_COMPRESSED_RGB8_ETC2 = 0x9274
GL_COMPRESSED_SRGB8_ETC2 = 0x9275
GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276
GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277
GL_COMPRESSED_RGBA8_ETC2_EAC = 0x9278
GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279
GL_COMPRESSED_R11_EAC = 0x9270
GL_COMPRESSED_SIGNED_R11_EAC = 0x9271
GL_COMPRESSED_RG11_EAC = 0x9272
GL_COMPRESSED_SIGNED_RG11_EAC = 0x9273
GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69
GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A
GL_MAX_ELEMENT_INDEX = 0x8D6B
GL_COMPUTE_SHADER = 0x91B9
GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB
GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC
GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD
GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262
GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263
GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264
GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265
GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266
GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x90EB
GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE
GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF
GL_COMPUTE_WORK_GROUP_SIZE = 0x8267
GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 0x90EC
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 0x90ED
GL_DISPATCH_INDIRECT_BUFFER = 0x90EE
GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x90EF
GL_COMPUTE_SHADER_BIT = 0x00000020
GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242
GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x8243
GL_DEBUG_CALLBACK_FUNCTION = 0x8244
GL_DEBUG_CALLBACK_USER_PARAM = 0x8245
GL_DEBUG_SOURCE_API = 0x8246
GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x8247
GL_DEBUG_SOURCE_SHADER_COMPILER = 0x8248
GL_DEBUG_SOURCE_THIRD_PARTY = 0x8249
GL_DEBUG_SOURCE_APPLICATION = 0x824A
GL_DEBUG_SOURCE_OTHER = 0x824B
GL_DEBUG_TYPE_ERROR = 0x824C
GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x824D
GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x824E
GL_DEBUG_TYPE_PORTABILITY = 0x824F
GL_DEBUG_TYPE_PERFORMANCE = 0x8250
GL_DEBUG_TYPE_OTHER = 0x8251
GL_MAX_DEBUG_MESSAGE_LENGTH = 0x9143
GL_MAX_DEBUG_LOGGED_MESSAGES = 0x9144
GL_DEBUG_LOGGED_MESSAGES = 0x9145
GL_DEBUG_SEVERITY_HIGH = 0x9146
GL_DEBUG_SEVERITY_MEDIUM = 0x9147
GL_DEBUG_SEVERITY_LOW = 0x9148
GL_DEBUG_TYPE_MARKER = 0x8268
GL_DEBUG_TYPE_PUSH_GROUP = 0x8269
GL_DEBUG_TYPE_POP_GROUP = 0x826A
GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B
GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x826C
GL_DEBUG_GROUP_STACK_DEPTH = 0x826D
GL_BUFFER = 0x82E0
GL_SHADER = 0x82E1
GL_PROGRAM = 0x82E2
GL_QUERY = 0x82E3
GL_PROGRAM_PIPELINE = 0x82E4
GL_SAMPLER = 0x82E6
GL_MAX_LABEL_LENGTH = 0x82E8
GL_DEBUG_OUTPUT = 0x92E0
GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002
GL_MAX_UNIFORM_LOCATIONS = 0x826E
GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x9310
GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x9311
GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x9312
GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x9313
GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x9314
GL_MAX_FRAMEBUFFER_WIDTH = 0x9315
GL_MAX_FRAMEBUFFER_HEIGHT = 0x9316
GL_MAX_FRAMEBUFFER_LAYERS = 0x9317
GL_MAX_FRAMEBUFFER_SAMPLES = 0x9318
GL_INTERNALFORMAT_SUPPORTED = 0x826F
GL_INTERNALFORMAT_PREFERRED = 0x8270
GL_INTERNALFORMAT_RED_SIZE = 0x8271
GL_INTERNALFORMAT_GREEN_SIZE = 0x8272
GL_INTERNALFORMAT_BLUE_SIZE = 0x8273
GL_INTERNALFORMAT_ALPHA_SIZE = 0x8274
GL_INTERNALFORMAT_DEPTH_SIZE = 0x8275
GL_INTERNALFORMAT_STENCIL_SIZE = 0x8276
GL_INTERNALFORMAT_SHARED_SIZE = 0x8277
GL_INTERNALFORMAT_RED_TYPE = 0x8278
GL_INTERNALFORMAT_GREEN_TYPE = 0x8279
GL_INTERNALFORMAT_BLUE_TYPE = 0x827A
GL_INTERNALFORMAT_ALPHA_TYPE = 0x827B
GL_INTERNALFORMAT_DEPTH_TYPE = 0x827C
GL_INTERNALFORMAT_STENCIL_TYPE = 0x827D
GL_MAX_WIDTH = 0x827E
GL_MAX_HEIGHT = 0x827F
GL_MAX_DEPTH = 0x8280
GL_MAX_LAYERS = 0x8281
GL_MAX_COMBINED_DIMENSIONS = 0x8282
GL_COLOR_COMPONENTS = 0x8283
GL_DEPTH_COMPONENTS = 0x8284
GL_STENCIL_COMPONENTS = 0x8285
GL_COLOR_RENDERABLE = 0x8286
GL_DEPTH_RENDERABLE = 0x8287
GL_STENCIL_RENDERABLE = 0x8288
GL_FRAMEBUFFER_RENDERABLE = 0x8289
GL_FRAMEBUFFER_RENDERABLE_LAYERED = 0x828A
GL_FRAMEBUFFER_BLEND = 0x828B
GL_READ_PIXELS = 0x828C
GL_READ_PIXELS_FORMAT = 0x828D
GL_READ_PIXELS_TYPE = 0x828E
GL_TEXTURE_IMAGE_FORMAT = 0x828F
GL_TEXTURE_IMAGE_TYPE = 0x8290
GL_GET_TEXTURE_IMAGE_FORMAT = 0x8291
GL_GET_TEXTURE_IMAGE_TYPE = 0x8292
GL_MIPMAP = 0x8293
GL_MANUAL_GENERATE_MIPMAP = 0x8294
GL_AUTO_GENERATE_MIPMAP = 0x8295
GL_COLOR_ENCODING = 0x8296
GL_SRGB_READ = 0x8297
GL_SRGB_WRITE = 0x8298
GL_FILTER = 0x829A
GL_VERTEX_TEXTURE = 0x829B
GL_TESS_CONTROL_TEXTURE = 0x829C
GL_TESS_EVALUATION_TEXTURE = 0x829D
GL_GEOMETRY_TEXTURE = 0x829E
GL_FRAGMENT_TEXTURE = 0x829F
GL_COMPUTE_TEXTURE = 0x82A0
GL_TEXTURE_SHADOW = 0x82A1
GL_TEXTURE_GATHER = 0x82A2
GL_TEXTURE_GATHER_SHADOW = 0x82A3
GL_SHADER_IMAGE_LOAD = 0x82A4
GL_SHADER_IMAGE_STORE = 0x82A5
GL_SHADER_IMAGE_ATOMIC = 0x82A6
GL_IMAGE_TEXEL_SIZE = 0x82A7
GL_IMAGE_COMPATIBILITY_CLASS = 0x82A8
GL_IMAGE_PIXEL_FORMAT = 0x82A9
GL_IMAGE_PIXEL_TYPE = 0x82AA
GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 0x82AC
GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 0x82AD
GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 0x82AE
GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 0x82AF
GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 0x82B1
GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 0x82B2
GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 0x82B3
GL_CLEAR_BUFFER = 0x82B4
GL_TEXTURE_VIEW = 0x82B5
GL_VIEW_COMPATIBILITY_CLASS = 0x82B6
GL_FULL_SUPPORT = 0x82B7
GL_CAVEAT_SUPPORT = 0x82B8
GL_IMAGE_CLASS_4_X_32 = 0x82B9
GL_IMAGE_CLASS_2_X_32 = 0x82BA
GL_IMAGE_CLASS_1_X_32 = 0x82BB
GL_IMAGE_CLASS_4_X_16 = 0x82BC
GL_IMAGE_CLASS_2_X_16 = 0x82BD
GL_IMAGE_CLASS_1_X_16 = 0x82BE
GL_IMAGE_CLASS_4_X_8 = 0x82BF
GL_IMAGE_CLASS_2_X_8 = 0x82C0
GL_IMAGE_CLASS_1_X_8 = 0x82C1
GL_IMAGE_CLASS_11_11_10 = 0x82C2
GL_IMAGE_CLASS_10_10_10_2 = 0x82C3
GL_VIEW_CLASS_128_BITS = 0x82C4
GL_VIEW_CLASS_96_BITS = 0x82C5
GL_VIEW_CLASS_64_BITS = 0x82C6
GL_VIEW_CLASS_48_BITS = 0x82C7
GL_VIEW_CLASS_32_BITS = 0x82C8
GL_VIEW_CLASS_24_BITS = 0x82C9
GL_VIEW_CLASS_16_BITS = 0x82CA
GL_VIEW_CLASS_8_BITS = 0x82CB
GL_VIEW_CLASS_S3TC_DXT1_RGB = 0x82CC
GL_VIEW_CLASS_S3TC_DXT1_RGBA = 0x82CD
GL_VIEW_CLASS_S3TC_DXT3_RGBA = 0x82CE
GL_VIEW_CLASS_S3TC_DXT5_RGBA = 0x82CF
GL_VIEW_CLASS_RGTC1_RED = 0x82D0
GL_VIEW_CLASS_RGTC2_RG = 0x82D1
GL_VIEW_CLASS_BPTC_UNORM = 0x82D2
GL_VIEW_CLASS_BPTC_FLOAT = 0x82D3
GL_UNIFORM = 0x92E1
GL_UNIFORM_BLOCK = 0x92E2
GL_PROGRAM_INPUT = 0x92E3
GL_PROGRAM_OUTPUT = 0x92E4
GL_BUFFER_VARIABLE = 0x92E5
GL_SHADER_STORAGE_BLOCK = 0x92E6
GL_VERTEX_SUBROUTINE = 0x92E8
GL_TESS_CONTROL_SUBROUTINE = 0x92E9
GL_TESS_EVALUATION_SUBROUTINE = 0x92EA
GL_GEOMETRY_SUBROUTINE = 0x92EB
GL_FRAGMENT_SUBROUTINE = 0x92EC
GL_COMPUTE_SUBROUTINE = 0x92ED
GL_VERTEX_SUBROUTINE_UNIFORM = 0x92EE
GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x92EF
GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x92F0
GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x92F1
GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x92F2
GL_COMPUTE_SUBROUTINE_UNIFORM = 0x92F3
GL_TRANSFORM_FEEDBACK_VARYING = 0x92F4
GL_ACTIVE_RESOURCES = 0x92F5
GL_MAX_NAME_LENGTH = 0x92F6
GL_MAX_NUM_ACTIVE_VARIABLES = 0x92F7
GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 0x92F8
GL_NAME_LENGTH = 0x92F9
GL_TYPE = 0x92FA
GL_ARRAY_SIZE = 0x92FB
GL_OFFSET = 0x92FC
GL_BLOCK_INDEX = 0x92FD
GL_ARRAY_STRIDE = 0x92FE
GL_MATRIX_STRIDE = 0x92FF
GL_IS_ROW_MAJOR = 0x9300
GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x9301
GL_BUFFER_BINDING = 0x9302
GL_BUFFER_DATA_SIZE = 0x9303
GL_NUM_ACTIVE_VARIABLES = 0x9304
GL_ACTIVE_VARIABLES = 0x9305
GL_REFERENCED_BY_VERTEX_SHADER = 0x9306
GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x9307
GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x9308
GL_REFERENCED_BY_GEOMETRY_SHADER = 0x9309
GL_REFERENCED_BY_FRAGMENT_SHADER = 0x930A
GL_REFERENCED_BY_COMPUTE_SHADER = 0x930B
GL_TOP_LEVEL_ARRAY_SIZE = 0x930C
GL_TOP_LEVEL_ARRAY_STRIDE = 0x930D
GL_LOCATION = 0x930E
GL_LOCATION_INDEX = 0x930F
GL_IS_PER_PATCH = 0x92E7
GL_SHADER_STORAGE_BUFFER = 0x90D2
GL_SHADER_STORAGE_BUFFER_BINDING = 0x90D3
GL_SHADER_STORAGE_BUFFER_START = 0x90D4
GL_SHADER_STORAGE_BUFFER_SIZE = 0x90D5
GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6
GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7
GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x90D8
GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9
GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA
GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB
GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC
GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD
GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE
GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x90DF
GL_SHADER_STORAGE_BARRIER_BIT = 0x00002000
GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x8F39
GL_DEPTH_STENCIL_TEXTURE_MODE = 0x90EA
GL_TEXTURE_BUFFER_OFFSET = 0x919D
GL_TEXTURE_BUFFER_SIZE = 0x919E
GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x919F
GL_TEXTURE_VIEW_MIN_LEVEL = 0x82DB
GL_TEXTURE_VIEW_NUM_LEVELS = 0x82DC
GL_TEXTURE_VIEW_MIN_LAYER = 0x82DD
GL_TEXTURE_VIEW_NUM_LAYERS = 0x82DE
GL_TEXTURE_IMMUTABLE_LEVELS = 0x82DF
GL_VERTEX_ATTRIB_BINDING = 0x82D4
GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5
GL_VERTEX_BINDING_DIVISOR = 0x82D6
GL_VERTEX_BINDING_OFFSET = 0x82D7
GL_VERTEX_BINDING_STRIDE = 0x82D8
GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9
GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA
GL_VERTEX_BINDING_BUFFER = 0x8F4F
PFNGLCLEARBUFFERDATAPROC = C(None, UInt, UInt, UInt, UInt, VoidP)
PFNGLCLEARBUFFERSUBDATAPROC = C(None, UInt, UInt, Size, Size, UInt, UInt,
                                VoidP)
PFNGLDISPATCHCOMPUTEPROC = C(None, UInt, UInt, UInt)
PFNGLDISPATCHCOMPUTEINDIRECTPROC = C(None, Size)
PFNGLCOPYIMAGESUBDATAPROC = C(None, UInt, UInt, Int, Int, Int, Int, UInt,
                              UInt, Int, Int, Int, Int, Int, Int, Int)
PFNGLFRAMEBUFFERPARAMETERIPROC = C(None, UInt, UInt, Int)
PFNGLGETFRAMEBUFFERPARAMETERIVPROC = C(None, UInt, UInt, P(Int))
PFNGLGETINTERNALFORMATI64VPROC = C(None, UInt, UInt, UInt, Int, P(Int64))
PFNGLINVALIDATETEXSUBIMAGEPROC = C(None, UInt, Int, Int, Int, Int, Int, Int,
                                   Int)
PFNGLINVALIDATETEXIMAGEPROC = C(None, UInt, Int)
PFNGLINVALIDATEBUFFERSUBDATAPROC = C(None, UInt, Size, Size)
PFNGLINVALIDATEBUFFERDATAPROC = C(None, UInt)
PFNGLINVALIDATEFRAMEBUFFERPROC = C(None, UInt, Int, P(UInt))
PFNGLINVALIDATESUBFRAMEBUFFERPROC = C(None, UInt, Int, P(UInt), Int, Int, Int,
                                      Int)
PFNGLMULTIDRAWARRAYSINDIRECTPROC = C(None, UInt, VoidP, Int, Int)
PFNGLMULTIDRAWELEMENTSINDIRECTPROC = C(None, UInt, UInt, VoidP, Int, Int)
PFNGLGETPROGRAMINTERFACEIVPROC = C(None, UInt, UInt, UInt, P(Int))
PFNGLGETPROGRAMRESOURCEINDEXPROC = C(UInt, UInt, UInt, CharP)
PFNGLGETPROGRAMRESOURCENAMEPROC = C(None, UInt, UInt, UInt, Int, P(Int),
                                    CharP)
PFNGLGETPROGRAMRESOURCEIVPROC = C(None, UInt, UInt, UInt, Int, P(UInt), Int,
                                  P(Int), P(Int))
PFNGLGETPROGRAMRESOURCELOCATIONPROC = C(Int, UInt, UInt, CharP)
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC = C(Int, UInt, UInt, CharP)
PFNGLSHADERSTORAGEBLOCKBINDINGPROC = C(None, UInt, UInt, UInt)
PFNGLTEXBUFFERRANGEPROC = C(None, UInt, UInt, UInt, Size, Size)
PFNGLTEXSTORAGE2DMULTISAMPLEPROC = C(None, UInt, Int, UInt, Int, Int, UByte)
PFNGLTEXSTORAGE3DMULTISAMPLEPROC = C(None, UInt, Int, UInt, Int, Int, Int,
                                     UByte)
PFNGLTEXTUREVIEWPROC = C(None, UInt, UInt, UInt, UInt, UInt, UInt, UInt, UInt)
PFNGLBINDVERTEXBUFFERPROC = C(None, UInt, UInt, Size, Int)
PFNGLVERTEXATTRIBFORMATPROC = C(None, UInt, Int, UInt, UByte, UInt)
PFNGLVERTEXATTRIBIFORMATPROC = C(None, UInt, Int, UInt, UInt)
PFNGLVERTEXATTRIBLFORMATPROC = C(None, UInt, Int, UInt, UInt)
PFNGLVERTEXATTRIBBINDINGPROC = C(None, UInt, UInt)
PFNGLVERTEXBINDINGDIVISORPROC = C(None, UInt, UInt)
PFNGLDEBUGMESSAGECONTROLPROC = C(None, UInt, UInt, UInt, Int, P(UInt), UByte)
PFNGLDEBUGMESSAGEINSERTPROC = C(None, UInt, UInt, UInt, UInt, Int, CharP)
PFNGLDEBUGMESSAGECALLBACKPROC = C(None, GLDEBUGPROC, VoidP)
PFNGLGETDEBUGMESSAGELOGPROC = C(UInt, UInt, Int, P(UInt), P(UInt), P(UInt),
                                P(UInt), P(Int), CharP)
PFNGLPUSHDEBUGGROUPPROC = C(None, UInt, UInt, Int, CharP)
PFNGLPOPDEBUGGROUPPROC = C(None)
PFNGLOBJECTLABELPROC = C(None, UInt, UInt, Int, CharP)
PFNGLGETOBJECTLABELPROC = C(None, UInt, UInt, Int, P(Int), CharP)
PFNGLOBJECTPTRLABELPROC = C(None, VoidP, Int, CharP)
PFNGLGETOBJECTPTRLABELPROC = C(None, VoidP, Int, P(Int), CharP)
glClearBufferData = E('glClearBufferData', None, UInt, UInt, UInt, UInt,
                      VoidP)
glClearBufferSubData = E('glClearBufferSubData', None, UInt, UInt, Size, Size,
                         UInt, UInt, VoidP)
glDispatchCompute = E('glDispatchCompute', None, UInt, UInt, UInt)
glDispatchComputeIndirect = E('glDispatchComputeIndirect', None, Size)
glCopyImageSubData = E('glCopyImageSubData', None, UInt, UInt, Int, Int, Int,
                       Int, UInt, UInt, Int, Int, Int, Int, Int, Int, Int)
glFramebufferParameteri = E('glFramebufferParameteri', None, UInt, UInt, Int)
glGetFramebufferParameteriv = E('glGetFramebufferParameteriv', None, UInt,
                                UInt, P(Int))
glGetInternalformati64v = E('glGetInternalformati64v', None, UInt, UInt, UInt,
                            Int, P(Int64))
glInvalidateTexSubImage = E('glInvalidateTexSubImage', None, UInt, Int, Int,
                            Int, Int, Int, Int, Int)
glInvalidateTexImage = E('glInvalidateTexImage', None, UInt, Int)
glInvalidateBufferSubData = E('glInvalidateBufferSubData', None, UInt, Size,
                              Size)
glInvalidateBufferData = E('glInvalidateBufferData', None, UInt)
glInvalidateFramebuffer = E('glInvalidateFramebuffer', None, UInt, Int,
                            P(UInt))
glInvalidateSubFramebuffer = E('glInvalidateSubFramebuffer', None, UInt, Int,
                               P(UInt), Int, Int, Int, Int)
glMultiDrawArraysIndirect = E('glMultiDrawArraysIndirect', None, UInt, VoidP,
                              Int, Int)
glMultiDrawElementsIndirect = E('glMultiDrawElementsIndirect', None, UInt,
                                UInt, VoidP, Int, Int)
glGetProgramInterfaceiv = E('glGetProgramInterfaceiv', None, UInt, UInt, UInt,
                            P(Int))
glGetProgramResourceIndex = E('glGetProgramResourceIndex', UInt, UInt, UInt,
                              CharP)
glGetProgramResourceName = E('glGetProgramResourceName', None, UInt, UInt,
                             UInt, Int, P(Int), CharP)
glGetProgramResourceiv = E('glGetProgramResourceiv', None, UInt, UInt, UInt,
                           Int, P(UInt), Int, P(Int), P(Int))
glGetProgramResourceLocation = E('glGetProgramResourceLocation', Int, UInt,
                                 UInt, CharP)
glGetProgramResourceLocationIndex = E('glGetProgramResourceLocationIndex',
                                      Int, UInt, UInt, CharP)
glShaderStorageBlockBinding = E('glShaderStorageBlockBinding', None, UInt,
                                UInt, UInt)
glTexBufferRange = E('glTexBufferRange', None, UInt, UInt, UInt, Size, Size)
glTexStorage2DMultisample = E('glTexStorage2DMultisample', None, UInt, Int,
                              UInt, Int, Int, UByte)
glTexStorage3DMultisample = E('glTexStorage3DMultisample', None, UInt, Int,
                              UInt, Int, Int, Int, UByte)
glTextureView = E('glTextureView', None, UInt, UInt, UInt, UInt, UInt, UInt,
                  UInt, UInt)
glBindVertexBuffer = E('glBindVertexBuffer', None, UInt, UInt, Size, Int)
glVertexAttribFormat = E('glVertexAttribFormat', None, UInt, Int, UInt, UByte,
                         UInt)
glVertexAttribIFormat = E('glVertexAttribIFormat', None, UInt, Int, UInt,
                          UInt)
glVertexAttribLFormat = E('glVertexAttribLFormat', None, UInt, Int, UInt,
                          UInt)
glVertexAttribBinding = E('glVertexAttribBinding', None, UInt, UInt)
glVertexBindingDivisor = E('glVertexBindingDivisor', None, UInt, UInt)
glDebugMessageControl = E('glDebugMessageControl', None, UInt, UInt, UInt,
                          Int, P(UInt), UByte)
glDebugMessageInsert = E('glDebugMessageInsert', None, UInt, UInt, UInt, UInt,
                         Int, CharP)
glDebugMessageCallback = E('glDebugMessageCallback', None, GLDEBUGPROC, VoidP)
glGetDebugMessageLog = E('glGetDebugMessageLog', UInt, UInt, Int, P(UInt),
                         P(UInt), P(UInt), P(UInt), P(Int), CharP)
glPushDebugGroup = E('glPushDebugGroup', None, UInt, UInt, Int, CharP)
glPopDebugGroup = E('glPopDebugGroup', None)
glObjectLabel = E('glObjectLabel', None, UInt, UInt, Int, CharP)
glGetObjectLabel = E('glGetObjectLabel', None, UInt, UInt, Int, P(Int), CharP)
glObjectPtrLabel = E('glObjectPtrLabel', None, VoidP, Int, CharP)
glGetObjectPtrLabel = E('glGetObjectPtrLabel', None, VoidP, Int, P(Int),
                        CharP)

__all__ = [
    'GL_VERSION_4_3', 'GLDEBUGPROC', 'GL_NUM_SHADING_LANGUAGE_VERSIONS',
    'GL_VERTEX_ATTRIB_ARRAY_LONG', 'GL_COMPRESSED_RGB8_ETC2',
    'GL_COMPRESSED_SRGB8_ETC2', 'GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2',
    'GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2',
    'GL_COMPRESSED_RGBA8_ETC2_EAC', 'GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC',
    'GL_COMPRESSED_R11_EAC', 'GL_COMPRESSED_SIGNED_R11_EAC',
    'GL_COMPRESSED_RG11_EAC', 'GL_COMPRESSED_SIGNED_RG11_EAC',
    'GL_PRIMITIVE_RESTART_FIXED_INDEX', 'GL_ANY_SAMPLES_PASSED_CONSERVATIVE',
    'GL_MAX_ELEMENT_INDEX', 'GL_COMPUTE_SHADER',
    'GL_MAX_COMPUTE_UNIFORM_BLOCKS', 'GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS',
    'GL_MAX_COMPUTE_IMAGE_UNIFORMS', 'GL_MAX_COMPUTE_SHARED_MEMORY_SIZE',
    'GL_MAX_COMPUTE_UNIFORM_COMPONENTS',
    'GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS', 'GL_MAX_COMPUTE_ATOMIC_COUNTERS',
    'GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS',
    'GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS',
    'GL_MAX_COMPUTE_WORK_GROUP_COUNT', 'GL_MAX_COMPUTE_WORK_GROUP_SIZE',
    'GL_COMPUTE_WORK_GROUP_SIZE',
    'GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER',
    'GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER',
    'GL_DISPATCH_INDIRECT_BUFFER', 'GL_DISPATCH_INDIRECT_BUFFER_BINDING',
    'GL_COMPUTE_SHADER_BIT', 'GL_DEBUG_OUTPUT_SYNCHRONOUS',
    'GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH', 'GL_DEBUG_CALLBACK_FUNCTION',
    'GL_DEBUG_CALLBACK_USER_PARAM', 'GL_DEBUG_SOURCE_API',
    'GL_DEBUG_SOURCE_WINDOW_SYSTEM', 'GL_DEBUG_SOURCE_SHADER_COMPILER',
    'GL_DEBUG_SOURCE_THIRD_PARTY', 'GL_DEBUG_SOURCE_APPLICATION',
    'GL_DEBUG_SOURCE_OTHER', 'GL_DEBUG_TYPE_ERROR',
    'GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR', 'GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR',
    'GL_DEBUG_TYPE_PORTABILITY', 'GL_DEBUG_TYPE_PERFORMANCE',
    'GL_DEBUG_TYPE_OTHER', 'GL_MAX_DEBUG_MESSAGE_LENGTH',
    'GL_MAX_DEBUG_LOGGED_MESSAGES', 'GL_DEBUG_LOGGED_MESSAGES',
    'GL_DEBUG_SEVERITY_HIGH', 'GL_DEBUG_SEVERITY_MEDIUM',
    'GL_DEBUG_SEVERITY_LOW', 'GL_DEBUG_TYPE_MARKER',
    'GL_DEBUG_TYPE_PUSH_GROUP', 'GL_DEBUG_TYPE_POP_GROUP',
    'GL_DEBUG_SEVERITY_NOTIFICATION', 'GL_MAX_DEBUG_GROUP_STACK_DEPTH',
    'GL_DEBUG_GROUP_STACK_DEPTH', 'GL_BUFFER', 'GL_SHADER', 'GL_PROGRAM',
    'GL_QUERY', 'GL_PROGRAM_PIPELINE', 'GL_SAMPLER', 'GL_MAX_LABEL_LENGTH',
    'GL_DEBUG_OUTPUT', 'GL_CONTEXT_FLAG_DEBUG_BIT',
    'GL_MAX_UNIFORM_LOCATIONS', 'GL_FRAMEBUFFER_DEFAULT_WIDTH',
    'GL_FRAMEBUFFER_DEFAULT_HEIGHT', 'GL_FRAMEBUFFER_DEFAULT_LAYERS',
    'GL_FRAMEBUFFER_DEFAULT_SAMPLES',
    'GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS',
    'GL_MAX_FRAMEBUFFER_WIDTH', 'GL_MAX_FRAMEBUFFER_HEIGHT',
    'GL_MAX_FRAMEBUFFER_LAYERS', 'GL_MAX_FRAMEBUFFER_SAMPLES',
    'GL_INTERNALFORMAT_SUPPORTED', 'GL_INTERNALFORMAT_PREFERRED',
    'GL_INTERNALFORMAT_RED_SIZE', 'GL_INTERNALFORMAT_GREEN_SIZE',
    'GL_INTERNALFORMAT_BLUE_SIZE', 'GL_INTERNALFORMAT_ALPHA_SIZE',
    'GL_INTERNALFORMAT_DEPTH_SIZE', 'GL_INTERNALFORMAT_STENCIL_SIZE',
    'GL_INTERNALFORMAT_SHARED_SIZE', 'GL_INTERNALFORMAT_RED_TYPE',
    'GL_INTERNALFORMAT_GREEN_TYPE', 'GL_INTERNALFORMAT_BLUE_TYPE',
    'GL_INTERNALFORMAT_ALPHA_TYPE', 'GL_INTERNALFORMAT_DEPTH_TYPE',
    'GL_INTERNALFORMAT_STENCIL_TYPE', 'GL_MAX_WIDTH', 'GL_MAX_HEIGHT',
    'GL_MAX_DEPTH', 'GL_MAX_LAYERS', 'GL_MAX_COMBINED_DIMENSIONS',
    'GL_COLOR_COMPONENTS', 'GL_DEPTH_COMPONENTS', 'GL_STENCIL_COMPONENTS',
    'GL_COLOR_RENDERABLE', 'GL_DEPTH_RENDERABLE', 'GL_STENCIL_RENDERABLE',
    'GL_FRAMEBUFFER_RENDERABLE', 'GL_FRAMEBUFFER_RENDERABLE_LAYERED',
    'GL_FRAMEBUFFER_BLEND', 'GL_READ_PIXELS', 'GL_READ_PIXELS_FORMAT',
    'GL_READ_PIXELS_TYPE', 'GL_TEXTURE_IMAGE_FORMAT', 'GL_TEXTURE_IMAGE_TYPE',
    'GL_GET_TEXTURE_IMAGE_FORMAT', 'GL_GET_TEXTURE_IMAGE_TYPE', 'GL_MIPMAP',
    'GL_MANUAL_GENERATE_MIPMAP', 'GL_AUTO_GENERATE_MIPMAP',
    'GL_COLOR_ENCODING', 'GL_SRGB_READ', 'GL_SRGB_WRITE', 'GL_FILTER',
    'GL_VERTEX_TEXTURE', 'GL_TESS_CONTROL_TEXTURE',
    'GL_TESS_EVALUATION_TEXTURE', 'GL_GEOMETRY_TEXTURE',
    'GL_FRAGMENT_TEXTURE', 'GL_COMPUTE_TEXTURE', 'GL_TEXTURE_SHADOW',
    'GL_TEXTURE_GATHER', 'GL_TEXTURE_GATHER_SHADOW', 'GL_SHADER_IMAGE_LOAD',
    'GL_SHADER_IMAGE_STORE', 'GL_SHADER_IMAGE_ATOMIC', 'GL_IMAGE_TEXEL_SIZE',
    'GL_IMAGE_COMPATIBILITY_CLASS', 'GL_IMAGE_PIXEL_FORMAT',
    'GL_IMAGE_PIXEL_TYPE', 'GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST',
    'GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST',
    'GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE',
    'GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE',
    'GL_TEXTURE_COMPRESSED_BLOCK_WIDTH', 'GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT',
    'GL_TEXTURE_COMPRESSED_BLOCK_SIZE', 'GL_CLEAR_BUFFER', 'GL_TEXTURE_VIEW',
    'GL_VIEW_COMPATIBILITY_CLASS', 'GL_FULL_SUPPORT', 'GL_CAVEAT_SUPPORT',
    'GL_IMAGE_CLASS_4_X_32', 'GL_IMAGE_CLASS_2_X_32', 'GL_IMAGE_CLASS_1_X_32',
    'GL_IMAGE_CLASS_4_X_16', 'GL_IMAGE_CLASS_2_X_16', 'GL_IMAGE_CLASS_1_X_16',
    'GL_IMAGE_CLASS_4_X_8', 'GL_IMAGE_CLASS_2_X_8', 'GL_IMAGE_CLASS_1_X_8',
    'GL_IMAGE_CLASS_11_11_10', 'GL_IMAGE_CLASS_10_10_10_2',
    'GL_VIEW_CLASS_128_BITS', 'GL_VIEW_CLASS_96_BITS',
    'GL_VIEW_CLASS_64_BITS', 'GL_VIEW_CLASS_48_BITS', 'GL_VIEW_CLASS_32_BITS',
    'GL_VIEW_CLASS_24_BITS', 'GL_VIEW_CLASS_16_BITS', 'GL_VIEW_CLASS_8_BITS',
    'GL_VIEW_CLASS_S3TC_DXT1_RGB', 'GL_VIEW_CLASS_S3TC_DXT1_RGBA',
    'GL_VIEW_CLASS_S3TC_DXT3_RGBA', 'GL_VIEW_CLASS_S3TC_DXT5_RGBA',
    'GL_VIEW_CLASS_RGTC1_RED', 'GL_VIEW_CLASS_RGTC2_RG',
    'GL_VIEW_CLASS_BPTC_UNORM', 'GL_VIEW_CLASS_BPTC_FLOAT', 'GL_UNIFORM',
    'GL_UNIFORM_BLOCK', 'GL_PROGRAM_INPUT', 'GL_PROGRAM_OUTPUT',
    'GL_BUFFER_VARIABLE', 'GL_SHADER_STORAGE_BLOCK', 'GL_VERTEX_SUBROUTINE',
    'GL_TESS_CONTROL_SUBROUTINE', 'GL_TESS_EVALUATION_SUBROUTINE',
    'GL_GEOMETRY_SUBROUTINE', 'GL_FRAGMENT_SUBROUTINE',
    'GL_COMPUTE_SUBROUTINE', 'GL_VERTEX_SUBROUTINE_UNIFORM',
    'GL_TESS_CONTROL_SUBROUTINE_UNIFORM',
    'GL_TESS_EVALUATION_SUBROUTINE_UNIFORM', 'GL_GEOMETRY_SUBROUTINE_UNIFORM',
    'GL_FRAGMENT_SUBROUTINE_UNIFORM', 'GL_COMPUTE_SUBROUTINE_UNIFORM',
    'GL_TRANSFORM_FEEDBACK_VARYING', 'GL_ACTIVE_RESOURCES',
    'GL_MAX_NAME_LENGTH', 'GL_MAX_NUM_ACTIVE_VARIABLES',
    'GL_MAX_NUM_COMPATIBLE_SUBROUTINES', 'GL_NAME_LENGTH', 'GL_TYPE',
    'GL_ARRAY_SIZE', 'GL_OFFSET', 'GL_BLOCK_INDEX', 'GL_ARRAY_STRIDE',
    'GL_MATRIX_STRIDE', 'GL_IS_ROW_MAJOR', 'GL_ATOMIC_COUNTER_BUFFER_INDEX',
    'GL_BUFFER_BINDING', 'GL_BUFFER_DATA_SIZE', 'GL_NUM_ACTIVE_VARIABLES',
    'GL_ACTIVE_VARIABLES', 'GL_REFERENCED_BY_VERTEX_SHADER',
    'GL_REFERENCED_BY_TESS_CONTROL_SHADER',
    'GL_REFERENCED_BY_TESS_EVALUATION_SHADER',
    'GL_REFERENCED_BY_GEOMETRY_SHADER', 'GL_REFERENCED_BY_FRAGMENT_SHADER',
    'GL_REFERENCED_BY_COMPUTE_SHADER', 'GL_TOP_LEVEL_ARRAY_SIZE',
    'GL_TOP_LEVEL_ARRAY_STRIDE', 'GL_LOCATION', 'GL_LOCATION_INDEX',
    'GL_IS_PER_PATCH', 'GL_SHADER_STORAGE_BUFFER',
    'GL_SHADER_STORAGE_BUFFER_BINDING', 'GL_SHADER_STORAGE_BUFFER_START',
    'GL_SHADER_STORAGE_BUFFER_SIZE', 'GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS',
    'GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS',
    'GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS',
    'GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS',
    'GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS',
    'GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS',
    'GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS',
    'GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS',
    'GL_MAX_SHADER_STORAGE_BLOCK_SIZE',
    'GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT',
    'GL_SHADER_STORAGE_BARRIER_BIT',
    'GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES',
    'GL_DEPTH_STENCIL_TEXTURE_MODE', 'GL_TEXTURE_BUFFER_OFFSET',
    'GL_TEXTURE_BUFFER_SIZE', 'GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT',
    'GL_TEXTURE_VIEW_MIN_LEVEL', 'GL_TEXTURE_VIEW_NUM_LEVELS',
    'GL_TEXTURE_VIEW_MIN_LAYER', 'GL_TEXTURE_VIEW_NUM_LAYERS',
    'GL_TEXTURE_IMMUTABLE_LEVELS', 'GL_VERTEX_ATTRIB_BINDING',
    'GL_VERTEX_ATTRIB_RELATIVE_OFFSET', 'GL_VERTEX_BINDING_DIVISOR',
    'GL_VERTEX_BINDING_OFFSET', 'GL_VERTEX_BINDING_STRIDE',
    'GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET', 'GL_MAX_VERTEX_ATTRIB_BINDINGS',
    'GL_VERTEX_BINDING_BUFFER', 'PFNGLCLEARBUFFERDATAPROC',
    'PFNGLCLEARBUFFERSUBDATAPROC', 'PFNGLDISPATCHCOMPUTEPROC',
    'PFNGLDISPATCHCOMPUTEINDIRECTPROC', 'PFNGLCOPYIMAGESUBDATAPROC',
    'PFNGLFRAMEBUFFERPARAMETERIPROC', 'PFNGLGETFRAMEBUFFERPARAMETERIVPROC',
    'PFNGLGETINTERNALFORMATI64VPROC', 'PFNGLINVALIDATETEXSUBIMAGEPROC',
    'PFNGLINVALIDATETEXIMAGEPROC', 'PFNGLINVALIDATEBUFFERSUBDATAPROC',
    'PFNGLINVALIDATEBUFFERDATAPROC', 'PFNGLINVALIDATEFRAMEBUFFERPROC',
    'PFNGLINVALIDATESUBFRAMEBUFFERPROC', 'PFNGLMULTIDRAWARRAYSINDIRECTPROC',
    'PFNGLMULTIDRAWELEMENTSINDIRECTPROC', 'PFNGLGETPROGRAMINTERFACEIVPROC',
    'PFNGLGETPROGRAMRESOURCEINDEXPROC', 'PFNGLGETPROGRAMRESOURCENAMEPROC',
    'PFNGLGETPROGRAMRESOURCEIVPROC', 'PFNGLGETPROGRAMRESOURCELOCATIONPROC',
    'PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC',
    'PFNGLSHADERSTORAGEBLOCKBINDINGPROC', 'PFNGLTEXBUFFERRANGEPROC',
    'PFNGLTEXSTORAGE2DMULTISAMPLEPROC', 'PFNGLTEXSTORAGE3DMULTISAMPLEPROC',
    'PFNGLTEXTUREVIEWPROC', 'PFNGLBINDVERTEXBUFFERPROC',
    'PFNGLVERTEXATTRIBFORMATPROC', 'PFNGLVERTEXATTRIBIFORMATPROC',
    'PFNGLVERTEXATTRIBLFORMATPROC', 'PFNGLVERTEXATTRIBBINDINGPROC',
    'PFNGLVERTEXBINDINGDIVISORPROC', 'PFNGLDEBUGMESSAGECONTROLPROC',
    'PFNGLDEBUGMESSAGEINSERTPROC', 'PFNGLDEBUGMESSAGECALLBACKPROC',
    'PFNGLGETDEBUGMESSAGELOGPROC', 'PFNGLPUSHDEBUGGROUPPROC',
    'PFNGLPOPDEBUGGROUPPROC', 'PFNGLOBJECTLABELPROC',
    'PFNGLGETOBJECTLABELPROC', 'PFNGLOBJECTPTRLABELPROC',
    'PFNGLGETOBJECTPTRLABELPROC', 'glClearBufferData', 'glClearBufferSubData',
    'glDispatchCompute', 'glDispatchComputeIndirect', 'glCopyImageSubData',
    'glFramebufferParameteri', 'glGetFramebufferParameteriv',
    'glGetInternalformati64v', 'glInvalidateTexSubImage',
    'glInvalidateTexImage', 'glInvalidateBufferSubData',
    'glInvalidateBufferData', 'glInvalidateFramebuffer',
    'glInvalidateSubFramebuffer', 'glMultiDrawArraysIndirect',
    'glMultiDrawElementsIndirect', 'glGetProgramInterfaceiv',
    'glGetProgramResourceIndex', 'glGetProgramResourceName',
    'glGetProgramResourceiv', 'glGetProgramResourceLocation',
    'glGetProgramResourceLocationIndex', 'glShaderStorageBlockBinding',
    'glTexBufferRange', 'glTexStorage2DMultisample',
    'glTexStorage3DMultisample', 'glTextureView', 'glBindVertexBuffer',
    'glVertexAttribFormat', 'glVertexAttribIFormat', 'glVertexAttribLFormat',
    'glVertexAttribBinding', 'glVertexBindingDivisor',
    'glDebugMessageControl', 'glDebugMessageInsert', 'glDebugMessageCallback',
    'glGetDebugMessageLog', 'glPushDebugGroup', 'glPopDebugGroup',
    'glObjectLabel', 'glGetObjectLabel', 'glObjectPtrLabel',
    'glGetObjectPtrLabel'
]
